package com.agentops.agent.domain;

public enum AgentStepType {
    CONTENT_PREPROCESSING, TICKET_CLASSIFICATION, RISK_EVALUATION, RESULT_PERSISTENCE,
    KNOWLEDGE_RETRIEVAL, REPLY_GENERATION, CITATION_VALIDATION, SUGGESTION_PERSISTENCE
}
